# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8f0617d065c12a698591bd5efdd1ff411dfbde6544be9a512efd803a077fc15b8f8ddcaa34819c84347d7e4a00b8b6dda86e67a533cf79add662db8f6d5996ef

test:
  secret_key_base: 529e32c5a32c4fc5fb3555be7fd531b73b2f18af2bd62ea2bfb20d3d01437d68498261aec4027fb9be87e9f102f71cf739050648ed5453e0e67c60deeab5fab2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
